ALTER TABLE GAME_RUN ADD COLUMN IF NOT EXISTS PHASE VARCHAR(30) NOT NULL DEFAULT 'DAY1_MORNING';
ALTER TABLE GAME_RUN ADD COLUMN IF NOT EXISTS CONFIRMED BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE GAME_RUN ADD COLUMN IF NOT EXISTS CURRENT_SCENE_ID BIGINT;
ALTER TABLE GAME_RUN ADD COLUMN IF NOT EXISTS MID_EVAL_TIER VARCHAR(2);
ALTER TABLE GAME_RUN ADD COLUMN IF NOT EXISTS MID_EVAL_EFFECT_UNTIL_TURN INT;
ALTER TABLE GAME_RUN ADD COLUMN IF NOT EXISTS FATIGUE INT NOT NULL DEFAULT 0;
